//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subprojdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Words
    {
        public long WId { get; set; }
        public string Text { get; set; }
        public long ChId { get; set; }
    
        public virtual Checks Checks { get; set; }
    }
}
